[project]
name = "arxiv-reading"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.6"
dependencies = ['pyzotero', 
    'bs4',
    'lxml',
    'feedparser'
    ]
